# Generated by Django 3.2.9 on 2021-12-09 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('main_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('wheight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(max_length=200, null=True)),
                ('unit_qnt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('retail_qnt', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('group', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('observation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doc_type', models.IntegerField()),
                ('doc_id1', models.CharField(max_length=20, null=True)),
                ('doc_id2', models.CharField(max_length=20, null=True)),
                ('extern_code', models.CharField(max_length=20, null=True)),
                ('since', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
