# Generated by Django 3.2.9 on 2021-12-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='since',
            field=models.DateField(null=True),
        ),
    ]
