# Generated by Django 3.2.9 on 2021-12-02 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_todo_api'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='Products',
        ),
    ]
