# Generated by Django 3.2.9 on 2021-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_api_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='products',
            name='task',
        ),
        migrations.AddField(
            model_name='products',
            name='group',
            field=models.DecimalField(decimal_places=0.2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='main_price',
            field=models.DecimalField(decimal_places=0.2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='observation',
            field=models.DecimalField(decimal_places=0.2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='retail_qnt',
            field=models.DecimalField(decimal_places=0.2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='unit_qnt',
            field=models.DecimalField(decimal_places=0.2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='wheight',
            field=models.DecimalField(decimal_places=0.2, max_digits=10, null=True),
        ),
    ]
